version: '2.2'
services:
  db:
    image: postgres
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - "./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh"
    environment:
      - POSTGRES_PASSWORD=postgrepassword